/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaas
 */
public class Main_panel extends javax.swing.JFrame {
    String librarianLogin="unsuccesful";
    /**
     * Creates new form Main_panel
     */
    public Main_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLibrarian = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        panelAdminLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        adminPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        panelAdminSection = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnAddLibrarian = new javax.swing.JButton();
        btnViewLibrarian = new javax.swing.JButton();
        btnDeleteLibrarian = new javax.swing.JButton();
        panelAddLibrarian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLibrarianName = new javax.swing.JTextField();
        txtLibrarianPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnBack1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        panelViewLibrarian = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibrarians = new javax.swing.JTable();
        panelDeleteLibrarian = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtLibrarianID = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        btnBack10 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtDeleteLibrarianName = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        panelLibrarianLogin = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtLibrarianName2 = new javax.swing.JTextField();
        txtLibrarianPassword2 = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnBack3 = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        panelLibrarianSection = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnlogoutLibrarian = new javax.swing.JButton();
        btnAddBooks = new javax.swing.JButton();
        btnViewBooks = new javax.swing.JButton();
        btnIssueBook = new javax.swing.JButton();
        btnViewIssuedBooks = new javax.swing.JButton();
        btnReurnBooks = new javax.swing.JButton();
        panelAddBooks = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnBack4 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        panelViewBooks = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnDeleteBookMain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBooks = new javax.swing.JTable();
        btnBack9 = new javax.swing.JButton();
        panelIssueBooks = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btnBack6 = new javax.swing.JButton();
        btnIssue = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        txtStudentContact = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        panelViewIssuedBooks = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnBack7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableIssuedBooks = new javax.swing.JTable();
        btnAddBook3 = new javax.swing.JButton();
        panelReturnBook = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TxtReturnBookID = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        btnBack8 = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        txtReturnStudentID = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        panelDeleteBook = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        TxtDeleteBookID = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        btnBack11 = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        txtDeleteBookName = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 733));

        panelParent.setMinimumSize(new java.awt.Dimension(1450, 320));
        panelParent.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelParent.setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setMinimumSize(new java.awt.Dimension(1400, 630));
        panelMain.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(32, 47, 90));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Librarry Management System");
        jLabel1.setOpaque(true);
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1450, 160));

        btnLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        btnLibrarian.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        btnLibrarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/study (1).png"))); // NOI18N
        btnLibrarian.setText("Librarian");
        btnLibrarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibrarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrarianActionPerformed(evt);
            }
        });
        panelMain.add(btnLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 256, 310));

        btnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin-with-cogwheels (1).png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        panelMain.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 256, 310));

        panelParent.add(panelMain, "card2");

        panelAdminLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelAdminLogin.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelAdminLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(32, 47, 90));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Login");
        jLabel2.setOpaque(true);
        panelAdminLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel3.setText("Admin Name");
        panelAdminLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 300, 60));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel4.setText("Admin Password");
        panelAdminLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 300, 60));

        txtAdminName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        txtAdminName.setBorder(null);
        panelAdminLogin.add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 300, 50));

        adminPassword.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        adminPassword.setBorder(null);
        adminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordActionPerformed(evt);
            }
        });
        panelAdminLogin.add(adminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 300, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelAdminLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 300, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelAdminLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 300, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelAdminLogin.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 160, 50));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelAdminLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 170, 50));

        panelParent.add(panelAdminLogin, "card2");

        panelAdminSection.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminSection.setMinimumSize(new java.awt.Dimension(1400, 580));
        panelAdminSection.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelAdminSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(32, 47, 90));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Admin Section");
        jLabel5.setOpaque(true);
        panelAdminSection.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panelAdminSection.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, 250, 250));

        btnAddLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        btnAddLibrarian.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnAddLibrarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/user.png"))); // NOI18N
        btnAddLibrarian.setText("Add Librarian");
        btnAddLibrarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddLibrarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibrarianActionPerformed(evt);
            }
        });
        panelAdminSection.add(btnAddLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 250));

        btnViewLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        btnViewLibrarian.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnViewLibrarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/business-card-of-a-man-with-contact-info.png"))); // NOI18N
        btnViewLibrarian.setText("View Librarian");
        btnViewLibrarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewLibrarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViewLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLibrarianActionPerformed(evt);
            }
        });
        panelAdminSection.add(btnViewLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 250, 250));

        btnDeleteLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteLibrarian.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnDeleteLibrarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/remove-user.png"))); // NOI18N
        btnDeleteLibrarian.setText("Delete Librarian");
        btnDeleteLibrarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteLibrarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLibrarianActionPerformed(evt);
            }
        });
        panelAdminSection.add(btnDeleteLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 250, 250));

        panelParent.add(panelAdminSection, "card2");

        panelAddLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        panelAddLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        panelAddLibrarian.setName(""); // NOI18N
        panelAddLibrarian.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelAddLibrarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(32, 47, 90));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Librarian");
        jLabel6.setOpaque(true);
        panelAddLibrarian.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText("Librarian Name");
        panelAddLibrarian.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 250, 60));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Librarian Password");
        panelAddLibrarian.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 60));

        txtLibrarianName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtLibrarianName.setBorder(null);
        panelAddLibrarian.add(txtLibrarianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 300, 50));

        txtLibrarianPassword.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtLibrarianPassword.setBorder(null);
        txtLibrarianPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibrarianPasswordActionPerformed(evt);
            }
        });
        panelAddLibrarian.add(txtLibrarianPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 300, 50));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelAddLibrarian.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 300, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelAddLibrarian.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 300, -1));

        btnBack1.setBackground(new java.awt.Color(255, 255, 255));
        btnBack1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        panelAddLibrarian.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 170, 50));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelAddLibrarian.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 170, 50));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setText("City");
        panelAddLibrarian.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 250, 60));

        txtCity.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtCity.setBorder(null);
        panelAddLibrarian.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 300, 50));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelAddLibrarian.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 300, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("Email");
        panelAddLibrarian.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 250, 60));

        txtEmail.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtEmail.setBorder(null);
        panelAddLibrarian.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 300, 50));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panelAddLibrarian.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 300, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setText("Contact Number");
        panelAddLibrarian.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 250, 60));

        txtContactNumber.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtContactNumber.setBorder(null);
        panelAddLibrarian.add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 300, 50));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panelAddLibrarian.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 300, -1));

        panelParent.add(panelAddLibrarian, "card2");

        panelViewLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        panelViewLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        panelViewLibrarian.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelViewLibrarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(32, 47, 90));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("View Librarian");
        jLabel12.setOpaque(true);
        panelViewLibrarian.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        btnBack2.setBackground(new java.awt.Color(255, 255, 255));
        btnBack2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        panelViewLibrarian.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 160, 50));

        tableLibrarians.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        tableLibrarians.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password", "City", "Email", "Contact Number"
            }
        ));
        jScrollPane1.setViewportView(tableLibrarians);

        panelViewLibrarian.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1080, -1));

        panelParent.add(panelViewLibrarian, "card2");

        panelDeleteLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        panelDeleteLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        panelDeleteLibrarian.setName(""); // NOI18N
        panelDeleteLibrarian.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelDeleteLibrarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(32, 47, 90));
        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Delete Librarian");
        jLabel33.setOpaque(true);
        panelDeleteLibrarian.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel34.setText("Librarian ID");
        panelDeleteLibrarian.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 250, 60));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel35.setText("Librarian Name");
        panelDeleteLibrarian.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 250, 60));

        txtLibrarianID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtLibrarianID.setBorder(null);
        panelDeleteLibrarian.add(txtLibrarianID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 300, 50));

        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));
        panelDeleteLibrarian.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 300, -1));

        btnBack10.setBackground(new java.awt.Color(255, 255, 255));
        btnBack10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack10.setText("Back");
        btnBack10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack10ActionPerformed(evt);
            }
        });
        panelDeleteLibrarian.add(btnBack10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 160, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelDeleteLibrarian.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 170, 50));

        txtDeleteLibrarianName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtDeleteLibrarianName.setBorder(null);
        panelDeleteLibrarian.add(txtDeleteLibrarianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 300, 50));

        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        panelDeleteLibrarian.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 300, -1));

        panelParent.add(panelDeleteLibrarian, "card2");

        panelLibrarianLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLibrarianLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelLibrarianLogin.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelLibrarianLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(32, 47, 90));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Librarian Login");
        jLabel14.setOpaque(true);
        panelLibrarianLogin.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel15.setText("Librarian Name");
        panelLibrarianLogin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 330, 60));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel16.setText("Librarian Password");
        panelLibrarianLogin.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 330, 60));

        txtLibrarianName2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        txtLibrarianName2.setBorder(null);
        panelLibrarianLogin.add(txtLibrarianName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 300, 50));

        txtLibrarianPassword2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        txtLibrarianPassword2.setBorder(null);
        txtLibrarianPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibrarianPassword2ActionPerformed(evt);
            }
        });
        panelLibrarianLogin.add(txtLibrarianPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 300, 50));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelLibrarianLogin.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 300, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        panelLibrarianLogin.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 300, -1));

        btnBack3.setBackground(new java.awt.Color(255, 255, 255));
        btnBack3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        panelLibrarianLogin.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 160, 50));

        btnLogin1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        panelLibrarianLogin.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 170, 50));

        panelParent.add(panelLibrarianLogin, "card2");

        panelLibrarianSection.setBackground(new java.awt.Color(255, 255, 255));
        panelLibrarianSection.setMinimumSize(new java.awt.Dimension(1400, 580));
        panelLibrarianSection.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelLibrarianSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(32, 47, 90));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Librarian Section");
        jLabel13.setOpaque(true);
        panelLibrarianSection.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        btnlogoutLibrarian.setBackground(new java.awt.Color(255, 255, 255));
        btnlogoutLibrarian.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnlogoutLibrarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/exit.png"))); // NOI18N
        btnlogoutLibrarian.setText("Logout");
        btnlogoutLibrarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlogoutLibrarian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnlogoutLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutLibrarianActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnlogoutLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 200, 200));

        btnAddBooks.setBackground(new java.awt.Color(255, 255, 255));
        btnAddBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnAddBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/book-with-add-button.png"))); // NOI18N
        btnAddBooks.setText("Add Books");
        btnAddBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBooksActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnAddBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 200, 200));

        btnViewBooks.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnViewBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/books-in-a-group-of-three-of-black-covers-from-side-view.png"))); // NOI18N
        btnViewBooks.setText("View Books");
        btnViewBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBooksActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnViewBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 200, 200));

        btnIssueBook.setBackground(new java.awt.Color(255, 255, 255));
        btnIssueBook.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnIssueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/clipboard-with-pencil-.png"))); // NOI18N
        btnIssueBook.setText("Issue Books");
        btnIssueBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIssueBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 200, 200));

        btnViewIssuedBooks.setBackground(new java.awt.Color(255, 255, 255));
        btnViewIssuedBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnViewIssuedBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/man-reading.png"))); // NOI18N
        btnViewIssuedBooks.setText("View Issued books");
        btnViewIssuedBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewIssuedBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViewIssuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIssuedBooksActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnViewIssuedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 200, 200));

        btnReurnBooks.setBackground(new java.awt.Color(255, 255, 255));
        btnReurnBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        btnReurnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/remove-book-button.png"))); // NOI18N
        btnReurnBooks.setText("Return Book");
        btnReurnBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReurnBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReurnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReurnBooksActionPerformed(evt);
            }
        });
        panelLibrarianSection.add(btnReurnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 200, 200));

        panelParent.add(panelLibrarianSection, "card2");

        panelAddBooks.setBackground(new java.awt.Color(255, 255, 255));
        panelAddBooks.setForeground(new java.awt.Color(255, 255, 255));
        panelAddBooks.setName(""); // NOI18N
        panelAddBooks.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelAddBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(32, 47, 90));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add Books");
        jLabel17.setOpaque(true);
        panelAddBooks.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel18.setText("Book Name");
        panelAddBooks.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 250, 60));

        txtBookName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtBookName.setBorder(null);
        panelAddBooks.add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 300, 50));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        panelAddBooks.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 300, -1));

        btnBack4.setBackground(new java.awt.Color(255, 255, 255));
        btnBack4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack4.setText("Back");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });
        panelAddBooks.add(btnBack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 160, 50));

        btnAdd1.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        panelAddBooks.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 170, 50));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel20.setText("Publisher");
        panelAddBooks.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 250, 60));

        txtPublisher.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtPublisher.setBorder(null);
        panelAddBooks.add(txtPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 300, 50));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        panelAddBooks.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 300, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel21.setText("Category");
        panelAddBooks.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 250, 60));

        txtCategory.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtCategory.setBorder(null);
        panelAddBooks.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 300, 50));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        panelAddBooks.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 300, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel22.setText("Quantity");
        panelAddBooks.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 250, 60));

        txtQuantity.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtQuantity.setBorder(null);
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        panelAddBooks.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 300, 50));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        panelAddBooks.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 300, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel23.setText("Author");
        panelAddBooks.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 60));

        txtAuthor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtAuthor.setBorder(null);
        panelAddBooks.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 300, 50));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        panelAddBooks.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 300, -1));

        panelParent.add(panelAddBooks, "card2");

        panelViewBooks.setBackground(new java.awt.Color(255, 255, 255));
        panelViewBooks.setForeground(new java.awt.Color(255, 255, 255));
        panelViewBooks.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        panelViewBooks.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelViewBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(32, 47, 90));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("View Books");
        jLabel19.setOpaque(true);
        panelViewBooks.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        btnDeleteBookMain.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteBookMain.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnDeleteBookMain.setText("Delete Book");
        btnDeleteBookMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteBookMain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteBookMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookMainActionPerformed(evt);
            }
        });
        panelViewBooks.add(btnDeleteBookMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 280, 170, 70));

        tableBooks.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        tableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Author", "Publisher", "Category", "Quantity", "Issued"
            }
        ));
        tableBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableBooks);

        panelViewBooks.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1080, -1));

        btnBack9.setBackground(new java.awt.Color(255, 255, 255));
        btnBack9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack9.setText("Back");
        btnBack9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack9ActionPerformed(evt);
            }
        });
        panelViewBooks.add(btnBack9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 170, 60));

        panelParent.add(panelViewBooks, "card2");

        panelIssueBooks.setBackground(new java.awt.Color(255, 255, 255));
        panelIssueBooks.setForeground(new java.awt.Color(255, 255, 255));
        panelIssueBooks.setName(""); // NOI18N
        panelIssueBooks.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelIssueBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(32, 47, 90));
        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Issue Books");
        jLabel24.setOpaque(true);
        panelIssueBooks.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel25.setText("Book ID");
        panelIssueBooks.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 250, 60));

        txtBookID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtBookID.setBorder(null);
        txtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIDActionPerformed(evt);
            }
        });
        panelIssueBooks.add(txtBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 300, 50));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        panelIssueBooks.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 300, -1));

        btnBack6.setBackground(new java.awt.Color(255, 255, 255));
        btnBack6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack6.setText("Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        panelIssueBooks.add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 180, 160, 50));

        btnIssue.setBackground(new java.awt.Color(255, 255, 255));
        btnIssue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnIssue.setText("Issue");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        panelIssueBooks.add(btnIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 170, 50));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel26.setText("Student Name");
        panelIssueBooks.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 60));

        txtStudentName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtStudentName.setBorder(null);
        panelIssueBooks.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 300, 50));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        panelIssueBooks.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 300, -1));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel27.setText("Student ID");
        panelIssueBooks.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 250, 60));

        txtStudentID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtStudentID.setBorder(null);
        panelIssueBooks.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 300, 50));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        panelIssueBooks.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 300, -1));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel28.setText("Student Contact");
        panelIssueBooks.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 250, 60));

        txtStudentContact.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtStudentContact.setBorder(null);
        txtStudentContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentContactActionPerformed(evt);
            }
        });
        panelIssueBooks.add(txtStudentContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 300, 50));

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        panelIssueBooks.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 300, -1));

        panelParent.add(panelIssueBooks, "card2");

        panelViewIssuedBooks.setBackground(new java.awt.Color(255, 255, 255));
        panelViewIssuedBooks.setForeground(new java.awt.Color(255, 255, 255));
        panelViewIssuedBooks.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelViewIssuedBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(32, 47, 90));
        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Issued Books");
        jLabel29.setOpaque(true);
        panelViewIssuedBooks.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        btnBack7.setBackground(new java.awt.Color(255, 255, 255));
        btnBack7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack7.setText("Back");
        btnBack7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack7ActionPerformed(evt);
            }
        });
        panelViewIssuedBooks.add(btnBack7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 140, 60));

        tableIssuedBooks.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        tableIssuedBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Student Name", "Student ID", "Student Contact", "Issued Date"
            }
        ));
        jScrollPane3.setViewportView(tableIssuedBooks);

        panelViewIssuedBooks.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1080, -1));

        btnAddBook3.setBackground(new java.awt.Color(255, 255, 255));
        btnAddBook3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnAddBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/give-card.png"))); // NOI18N
        btnAddBook3.setText("Return Book");
        btnAddBook3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddBook3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBook3ActionPerformed(evt);
            }
        });
        panelViewIssuedBooks.add(btnAddBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 290, 140, 120));

        panelParent.add(panelViewIssuedBooks, "card2");

        panelReturnBook.setBackground(new java.awt.Color(255, 255, 255));
        panelReturnBook.setName(""); // NOI18N
        panelReturnBook.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setBackground(new java.awt.Color(32, 47, 90));
        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Return Book");
        jLabel30.setOpaque(true);
        panelReturnBook.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel31.setText("Book ID");
        panelReturnBook.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 250, 60));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel32.setText("Student ID");
        panelReturnBook.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 250, 60));

        TxtReturnBookID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        TxtReturnBookID.setBorder(null);
        panelReturnBook.add(TxtReturnBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 300, 50));

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        panelReturnBook.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 300, -1));

        btnBack8.setBackground(new java.awt.Color(255, 255, 255));
        btnBack8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack8.setText("Back");
        btnBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack8ActionPerformed(evt);
            }
        });
        panelReturnBook.add(btnBack8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 160, 50));

        btnReturn.setBackground(new java.awt.Color(255, 255, 255));
        btnReturn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        panelReturnBook.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 170, 50));

        txtReturnStudentID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtReturnStudentID.setBorder(null);
        panelReturnBook.add(txtReturnStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 300, 50));

        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        panelReturnBook.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 300, -1));

        panelParent.add(panelReturnBook, "card2");

        panelDeleteBook.setBackground(new java.awt.Color(255, 255, 255));
        panelDeleteBook.setName(""); // NOI18N
        panelDeleteBook.setPreferredSize(new java.awt.Dimension(1400, 700));
        panelDeleteBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(32, 47, 90));
        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Delete Book");
        jLabel36.setOpaque(true);
        panelDeleteBook.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel37.setText("Book ID");
        panelDeleteBook.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 250, 60));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel38.setText("Book Name");
        panelDeleteBook.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 250, 60));

        TxtDeleteBookID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        TxtDeleteBookID.setBorder(null);
        panelDeleteBook.add(TxtDeleteBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 300, 50));

        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        panelDeleteBook.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 300, -1));

        btnBack11.setBackground(new java.awt.Color(255, 255, 255));
        btnBack11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnBack11.setText("Back");
        btnBack11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack11ActionPerformed(evt);
            }
        });
        panelDeleteBook.add(btnBack11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 160, 50));

        btnDeleteBook.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteBook.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnDeleteBook.setText("Delete");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });
        panelDeleteBook.add(btnDeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 170, 50));

        txtDeleteBookName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtDeleteBookName.setBorder(null);
        panelDeleteBook.add(txtDeleteBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 300, 50));

        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        panelDeleteBook.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 300, -1));

        panelParent.add(panelDeleteBook, "card2");

        getContentPane().add(panelParent, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrarianActionPerformed
       panelParent.removeAll();
        panelParent.add(panelLibrarianLogin);
        panelParent.repaint();
        panelParent.revalidate();
        
    }//GEN-LAST:event_btnLibrarianActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        panelParent.removeAll();
        panelParent.add(panelAdminLogin);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void adminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int alert=JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Logout?","Library Management System", JOptionPane.YES_NO_OPTION);
        if(alert==JOptionPane.YES_OPTION){
            panelParent.removeAll();
            panelParent.add(panelMain);
            panelParent.repaint();
            panelParent.revalidate();
        }
        if(alert==JOptionPane.NO_OPTION){
            panelParent.removeAll();
            panelParent.add(panelAdminSection);
            panelParent.repaint();
            panelParent.revalidate();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibrarianActionPerformed
         panelParent.removeAll();
             panelParent.add(panelAddLibrarian);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnAddLibrarianActionPerformed
    public void loadTableViewLibrarians(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM librarians ");
            ResultSet rs = ps.executeQuery();
            
            ArrayList<Librarian> alist = new ArrayList<Librarian>(); 
            
            while(rs.next()){
                Librarian l =new Librarian(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getInt(6));
                alist.add(l);
            }
            DefaultTableModel model = (DefaultTableModel) tableLibrarians.getModel();
            Object[] row = new Object[6];
            for(int i=0;i<alist.size();i++){
                row[0]=alist.get(i).id;
                row[1]=alist.get(i).name;
                row[2]=alist.get(i).password;
                row[3]=alist.get(i).city;
                row[4]=alist.get(i).email;
                row[5]=alist.get(i).contact;
                
                model.addRow(row);
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnViewLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLibrarianActionPerformed
         panelParent.removeAll();
             panelParent.add(panelViewLibrarian);
             panelParent.repaint();
             panelParent.revalidate();
             
             loadTableViewLibrarians();
             
    }//GEN-LAST:event_btnViewLibrarianActionPerformed

    private void btnDeleteLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLibrarianActionPerformed
        panelParent.removeAll();
             panelParent.add(panelDeleteLibrarian);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnDeleteLibrarianActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        panelParent.removeAll();
             panelParent.add(panelMain);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String name="admin";
        String password = "admin";
        
        if((password.equals(txtAdminName.getText()))&& (name.equals(adminPassword.getText()))){
            
            
            panelParent.removeAll();
             panelParent.add(panelAdminSection);
             panelParent.repaint();
             panelParent.revalidate();
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid Details!","Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        panelParent.removeAll();
             panelParent.add(panelAdminSection);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name,password,city,email;
        int contact;
        name=txtLibrarianName.getText();
        password= txtLibrarianPassword.getText();
        city=txtCity.getText();
        email=txtEmail.getText();
        contact=Integer.parseInt(txtContactNumber.getText());
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            PreparedStatement ps = conn.prepareStatement("INSERT INTO librarians (name,password,city,email,contact) VALUES (?,?,?,?,?)");
            ps.setString(1,name);
            ps.setString(2,password);
            ps.setString(3, city);
            ps.setString(4, email);
            ps.setInt(5, contact);
            int i=ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Librarian Added Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
            
            DefaultTableModel model=(DefaultTableModel) tableLibrarians.getModel();
            model.setRowCount(0);
        
            panelParent.removeAll();
            panelParent.add(panelViewLibrarian);
            panelParent.repaint();
            panelParent.revalidate();
        
        
            loadTableViewLibrarians();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtLibrarianPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibrarianPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianPasswordActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
         panelParent.removeAll();
        panelParent.add(panelAdminSection);
        panelParent.repaint();
        panelParent.revalidate();
        
        DefaultTableModel model=(DefaultTableModel) tableLibrarians.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnlogoutLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutLibrarianActionPerformed
        
        
        int alert=JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Logout?","Library Management System", JOptionPane.YES_NO_OPTION);
        if(alert==JOptionPane.YES_OPTION){
            panelParent.removeAll();
            panelParent.add(panelMain);
            panelParent.repaint();
            panelParent.revalidate();
        }
        if(alert==JOptionPane.NO_OPTION){
            panelParent.removeAll();
            panelParent.add(panelLibrarianSection);
            panelParent.repaint();
            panelParent.revalidate();
        }
    }//GEN-LAST:event_btnlogoutLibrarianActionPerformed

    private void btnAddBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBooksActionPerformed
        panelParent.removeAll();
        panelParent.add(panelAddBooks);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnAddBooksActionPerformed
    public void loadTableViewBooks(){
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM books ");
            ResultSet rs = ps.executeQuery();
            
            ArrayList<Book> alist = new ArrayList<Book>(); 
            
            while(rs.next()){
                Book b =new Book(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getInt(6),rs.getInt(7));
                alist.add(b);
            }
            DefaultTableModel model = (DefaultTableModel) tableBooks.getModel();
            Object[] row = new Object[7];
            for(int i=0;i<alist.size();i++){
                row[0]=alist.get(i).ID;
                row[1]=alist.get(i).name;
                row[2]=alist.get(i).author;
                row[3]=alist.get(i).publisher;
                row[4]=alist.get(i).category;
                row[5]=alist.get(i).quantity;
                row[6]=alist.get(i).issued;
                model.addRow(row);
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBooksActionPerformed
            panelParent.removeAll();
             panelParent.add(panelViewBooks);
             panelParent.repaint();
             panelParent.revalidate();
             
           loadTableViewBooks();
    }//GEN-LAST:event_btnViewBooksActionPerformed

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed
        panelParent.removeAll();
        panelParent.add(panelIssueBooks);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnIssueBookActionPerformed
    public void loadIssuedBooks(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM issuedbooks ");
            ResultSet rs = ps.executeQuery();
            
            ArrayList<IssuedBook> alist = new ArrayList<IssuedBook>(); 
            
            while(rs.next()){
                IssuedBook ib =new IssuedBook(rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4),rs.getString(5));
                alist.add(ib);
            }
            DefaultTableModel model = (DefaultTableModel) tableIssuedBooks.getModel();
            Object[] row = new Object[5];
            for(int i=0;i<alist.size();i++){
                row[0]=alist.get(i).bookID;
                row[1]=alist.get(i).studentName;
                row[2]=alist.get(i).studentID;
                row[3]=alist.get(i).contact;
                row[4]=alist.get(i).date;
                
                model.addRow(row);
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        } 
    }
    private void btnViewIssuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIssuedBooksActionPerformed
        panelParent.removeAll();
        panelParent.add(panelViewIssuedBooks);
        panelParent.repaint();
        panelParent.revalidate();
        
        loadIssuedBooks();
    }//GEN-LAST:event_btnViewIssuedBooksActionPerformed

    private void btnReurnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReurnBooksActionPerformed
         panelParent.removeAll();
             panelParent.add(panelReturnBook);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnReurnBooksActionPerformed

    private void txtLibrarianPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibrarianPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianPassword2ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
            panelParent.removeAll();
             panelParent.add(panelMain);
             panelParent.repaint();
             panelParent.revalidate();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        String password,name;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            PreparedStatement stmt =  conn.prepareStatement("SELECT name,password FROM librarians");
            ResultSet rs= stmt.executeQuery();
            while(rs.next()){
                name = rs.getString(1);
                password = rs.getString(2);
                
                if(name.equals(txtLibrarianName2.getText())&& password.equals(txtLibrarianPassword2.getText())){
                    this.librarianLogin="successful";
                    panelParent.removeAll();
                    panelParent.add(panelLibrarianSection);
                    panelParent.repaint();
                    panelParent.revalidate();
                }
                
                
            }
            if(!librarianLogin.equals("successful")){
                JOptionPane.showMessageDialog(null,"Invalid login details","Library Management System", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        DefaultTableModel model=(DefaultTableModel) tableBooks.getModel();
        model.setRowCount(0);
        
        panelParent.removeAll();
        panelParent.add(panelLibrarianSection);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        String name,publisher,category,author;
        int ID,quantity,issued;
        
        name=txtBookName.getText();
        publisher=txtPublisher.getText();
        category=txtCategory.getText();
        author=txtAuthor.getText();
        quantity=Integer.parseInt(txtQuantity.getText());
        issued=0; 
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            
            PreparedStatement ps = con.prepareStatement("INSERT INTO books (name,author,publisher,category,quantity,issued) VALUES (?,?,?,?,?,?)");
            ps.setString(1, name);
            ps.setString(2, author);
            ps.setString(3, publisher);
            ps.setString(4, category);
            ps.setInt(5,quantity);
            ps.setInt(6,issued);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Book Added Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
            
            // Set row count of viewBooks to 0
            DefaultTableModel model=(DefaultTableModel) tableBooks.getModel();
            model.setRowCount(0);
            loadTableViewBooks();
             
            //Reload
            panelParent.removeAll();
            panelParent.add(panelViewBooks);
            panelParent.repaint();
            panelParent.revalidate();
        
            
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnDeleteBookMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookMainActionPerformed
        panelParent.removeAll();
        panelParent.add(panelDeleteBook);
        panelParent.repaint();
        panelParent.revalidate();
        
        
    }//GEN-LAST:event_btnDeleteBookMainActionPerformed

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        DefaultTableModel model=(DefaultTableModel) tableIssuedBooks.getModel();
        model.setRowCount(0);
        
        panelParent.removeAll();
        panelParent.add(panelLibrarianSection);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnBack6ActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        String sName;
        int bookID,sID,contact;
        int issued;
                
        sName=txtStudentName.getText();
        sID=Integer.parseInt(txtStudentID.getText());
        bookID=Integer.parseInt(txtBookID.getText());
        contact=Integer.parseInt(txtStudentContact.getText());
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement("INSERT INTO issuedbooks  VALUES (?,?,?,?,?)");
            ps.setInt(1,bookID);
            ps.setString(2,sName);
            ps.setInt(3, sID);
            ps.setInt(4, contact);
            ps.setDate(5,new java.sql.Date(new java.util.Date().getTime()));
            int i=ps.executeUpdate();
            
            try{
                PreparedStatement pst= conn.prepareStatement("SELECT issued FROM books WHERE ID=?");
                pst.setInt(1, bookID);
                ResultSet r=pst.executeQuery();
                
                while(r.next()){
                     issued= r.getInt(1)+1;
                     PreparedStatement pst1= conn.prepareStatement("UPDATE books SET issued=? WHERE ID=? ");
                    pst1.setInt(1, issued);
                    pst1.setInt(2, bookID);
                    pst1.executeUpdate();
                }
                conn.setAutoCommit(true);
                
                JOptionPane.showMessageDialog(null,"Book Issued Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
                //Clear tableIssuedBooks
                DefaultTableModel model=(DefaultTableModel) tableIssuedBooks.getModel();
                model.setRowCount(0);
                panelParent.removeAll();
                panelParent.add(panelViewIssuedBooks);
                panelParent.repaint();
                panelParent.revalidate();
        
                loadIssuedBooks();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIssueActionPerformed

    private void txtStudentContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentContactActionPerformed

    private void btnBack7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack7ActionPerformed
        panelParent.removeAll();
        panelParent.add(panelLibrarianSection);
        panelParent.repaint();
        panelParent.revalidate();
        
        DefaultTableModel model=(DefaultTableModel) tableIssuedBooks.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnBack7ActionPerformed

    private void txtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIDActionPerformed

    private void btnBack8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack8ActionPerformed
        DefaultTableModel model=(DefaultTableModel) tableIssuedBooks.getModel();
        model.setRowCount(0);
        
        panelParent.removeAll();
        panelParent.add(panelLibrarianSection);
        panelParent.repaint();
        panelParent.revalidate();
    }//GEN-LAST:event_btnBack8ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        int bID,sID,issued;
        bID =Integer.parseInt(TxtReturnBookID.getText());
        sID =Integer.parseInt(txtReturnStudentID.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            con.setAutoCommit(false);
            PreparedStatement ps = con.prepareStatement("DELETE FROM issuedbooks WHERE bookID=? AND studentID=?");
            ps.setInt(1, bID);
            ps.setInt(2, sID);
            ps.executeUpdate();
            
            PreparedStatement ps2 = con.prepareStatement("SELECT issued FROM books WHERE ID=?");
            ps2.setInt(1, bID);
            ResultSet rs= ps2.executeQuery();
            while(rs.next()){
                issued = rs.getInt(1) - 1 ;
                PreparedStatement ps1 = con.prepareStatement("UPDATE books SET issued=? WHERE ID=?");
                ps1.setInt(1, issued );
                ps1.setInt(2, bID);
                ps1.executeUpdate();
            }
            con.setAutoCommit(true);
            JOptionPane.showMessageDialog(null,"Book Returned Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnBack9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack9ActionPerformed
        
        
        panelParent.removeAll();
        panelParent.add(panelLibrarianSection);
        panelParent.repaint();
        panelParent.revalidate();
        
        // Set row count of viewBooks to 0
        DefaultTableModel model=(DefaultTableModel) tableBooks.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnBack9ActionPerformed

    private void btnBack10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack10ActionPerformed
        panelParent.removeAll();
        panelParent.add(panelAdminSection);
        panelParent.repaint();
        panelParent.revalidate();
        
    }//GEN-LAST:event_btnBack10ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int libID;
        String libName =txtDeleteLibrarianName.getText();
        libID =Integer.parseInt(txtLibrarianID.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            
            PreparedStatement ps = con.prepareStatement("DELETE FROM librarians WHERE name=? AND ID=?");
            ps.setString(1, libName);
            ps.setInt(2, libID);
            ps.executeUpdate();
                        
            JOptionPane.showMessageDialog(null,"Librarian Deleted Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
            
            panelParent.removeAll();
            panelParent.add(panelAdminSection);
            panelParent.repaint();
            panelParent.revalidate();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBook3ActionPerformed
            panelParent.removeAll();
            panelParent.add(panelReturnBook);
            panelParent.repaint();
            panelParent.revalidate();
    }//GEN-LAST:event_btnAddBook3ActionPerformed

    private void btnBack11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack11ActionPerformed
        panelParent.removeAll();
            panelParent.add(panelViewBooks);
            panelParent.repaint();
            panelParent.revalidate();
    }//GEN-LAST:event_btnBack11ActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        int bookID;
        String bookName =txtDeleteBookName.getText();
        bookID =Integer.parseInt(TxtDeleteBookID.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","");
            
            PreparedStatement ps = con.prepareStatement("DELETE FROM books WHERE name=? AND ID=?");
            ps.setString(1, bookName);
            ps.setInt(2, bookID);
            ps.executeUpdate();
                        
            JOptionPane.showMessageDialog(null,"Book Deleted Successfully.","Library Management System", JOptionPane.PLAIN_MESSAGE);
            
            // Set row count of viewBooks to 0
            DefaultTableModel model=(DefaultTableModel) tableBooks.getModel();
            model.setRowCount(0);
            loadTableViewBooks();
            
            panelParent.removeAll();
            panelParent.add(panelViewBooks);
            panelParent.repaint();
            panelParent.revalidate();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e,"Library Management System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDeleteBookID;
    private javax.swing.JTextField TxtReturnBookID;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddBook3;
    private javax.swing.JButton btnAddBooks;
    private javax.swing.JButton btnAddLibrarian;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack10;
    private javax.swing.JButton btnBack11;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnBack7;
    private javax.swing.JButton btnBack8;
    private javax.swing.JButton btnBack9;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnDeleteBookMain;
    private javax.swing.JButton btnDeleteLibrarian;
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JButton btnLibrarian;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReurnBooks;
    private javax.swing.JButton btnViewBooks;
    private javax.swing.JButton btnViewIssuedBooks;
    private javax.swing.JButton btnViewLibrarian;
    private javax.swing.JButton btnlogoutLibrarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelAddBooks;
    private javax.swing.JPanel panelAddLibrarian;
    private javax.swing.JPanel panelAdminLogin;
    private javax.swing.JPanel panelAdminSection;
    private javax.swing.JPanel panelDeleteBook;
    private javax.swing.JPanel panelDeleteLibrarian;
    private javax.swing.JPanel panelIssueBooks;
    private javax.swing.JPanel panelLibrarianLogin;
    private javax.swing.JPanel panelLibrarianSection;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelReturnBook;
    private javax.swing.JPanel panelViewBooks;
    private javax.swing.JPanel panelViewIssuedBooks;
    private javax.swing.JPanel panelViewLibrarian;
    private javax.swing.JTable tableBooks;
    private javax.swing.JTable tableIssuedBooks;
    private javax.swing.JTable tableLibrarians;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDeleteBookName;
    private javax.swing.JTextField txtDeleteLibrarianName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLibrarianID;
    private javax.swing.JTextField txtLibrarianName;
    private javax.swing.JTextField txtLibrarianName2;
    private javax.swing.JPasswordField txtLibrarianPassword;
    private javax.swing.JPasswordField txtLibrarianPassword2;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReturnStudentID;
    private javax.swing.JTextField txtStudentContact;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables

    private static class Librarian {
        String name,password,city,email;
        int id,contact;
        public Librarian(int i,String n,String p,String c,String e,int con) {
            this.id=i;
            this.name=n;
            this.password=p;
            this.city=c;
            this.email=e;
            this.contact=con;
        }
    }
}
